source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.2'
pod 'RNGridMenu', '~> 0.1.3'
pod 'IQKeyboardManager', '~> 3.2.0'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
